### ISSUE TITLE
Aufgabe 03 Feedback

### ISSUE THREAD

**Issue by MarkusDamm** [elenajenny/EIA2#2]
Hallo Elena und Celine,
das Hinzufügen und Entfernen von Auswahlmöglichkeiten funktioniert ja ganz in Ordnung. Ihr habt ein interessantes Konzept, bei dem ihr immer der Übersicht das hinzufügt, was gerade geändert wurde. Funktioniert ja leider nur unter ganz bestimmten Bedingungen.
An sich ist das Konzept in Ordnung, jedoch Fehleranfällig. Darum noch einige Hinweise
- in der Skizze, macht es Sinn sowas wie die Menge in Textfeldern angeben zu lassen?
- der Preis sollte auch lieber von euch vorgegeben werden, da der Kunde sonst Geld für die ihm erbrachte Leistung verlangen könnte
- im AD bei displayOrder scheint ihr eine Schleife verwenden zu wollen, wo aber nur ein Item bearbeitet wird. Eine Schleife macht da keinen Sinn
- manche Eingaben gehören zusammen oder beeinflussen andere. Mit eurer Vorgehensweise müsstet ihr also die bisherigen Eingaben überprüfen und dementsprechend bearbeiten. Das wäre zu viel Aufwand, weshalb eine andere Vorgehensweise ratsam wäre

**Comment by elenajenny** [comment]
Hallo,
also wir haben uns das bei der Einkaufsliste so vorgestellt, dass man als Kunde gerne eingeben möchte was man genau möchte und das es beim Einkauf hilfreich ist, wenn der Kunde hinschreibt, zum Beispiel ich möchte genau diese Äpfel die wiegen 500g und kosten schon immer .... Preis. Wenn der Preis nicht stimmen sollte oder zu wenig angegeben wurde dann sollte eine nachträgliche Rechnung gestellt werden. 
Wir haben versucht den value mit FormElements zu bekommen, das hat aber nicht funktioniert, deshalb mussten wir uns den value dann über Event.target holen. 

So hatten wir uns das vorgestellt... 

Was genau sollen wir jetzt tun? Die Punkte die du angegeben hast, verbessern oder was genau schlägst du jetzt vor, da wir ja an dieser Aufgabe weiterarbeiten werden.

**Comment by MarkusDamm** [comment]
Für Zahlen, wie sie bei einer Mengenangabe oder dem Preis genutzt werden, gibt es den Input-type "number".
Was dringend beheben werden sollte ist, dass Einträge mehrfach erscheinen oder sogar widersprüchlich zu anderen aufgelisteten Einträgen sein können. Dafür wäre die Vorgehensweise mit _FormData_ besser geeignet.
